---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bifrost-lan-tls
  namespace: bifrost
spec:
  secretName: bifrost-lan-tls
  issuerRef:
    name: lan-ca
    kind: ClusterIssuer
  dnsNames:
    - bifrost.lan
