keys:
  - &desktop age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
  - &framework13 age1upzxx3l4ce5e0mcje59sekkwpcnczusxs0sgn8emyuv39q8gg99s5uupkn
  - &router age132wl9vjpn58utdnenmupg6d7v0dugkxphf9qlcf3w3ysvkur3yjqzdhwv3
  # k3s cluster servers
  - &boromir age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
  - &samwise age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
  - &theoden age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
creation_rules:
  - path_regex: secrets/work-vpn.conf
    key_groups:
      - age:
          - *desktop
          - *framework13
  - path_regex: secrets/emacs/*
    key_groups:
      - age:
          - *desktop
          - *framework13
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *desktop
          - *framework13
          - *router
          - *boromir
          - *samwise
          - *theoden
  # Kubernetes secrets - encrypted for k3s cluster nodes + desktop for editing
  - path_regex: k8s/.*/.*secret.*\.yaml$
    key_groups:
      - age:
          - *desktop
          - *boromir
          - *samwise
          - *theoden
