---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voicemail-secrets
  namespace: voicemail-receiver
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: voicemail-secrets
    creationPolicy: Owner
  data:
    - secretKey: WEBHOOK_BASE_URL
      remoteRef:
        key: k8s/voicemail-receiver
        property: WEBHOOK_BASE_URL
    - secretKey: TELNYX_API_KEY
      remoteRef:
        key: k8s/voicemail-receiver
        property: TELNYX_API_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voicemail-ntfy-proxy
  namespace: voicemail-receiver
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: voicemail-ntfy-proxy
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        Caddyfile: |
          http://127.0.0.1:2586 {
              reverse_proxy https://ntfy.dimensiondoor.xyz {
                  header_up Host ntfy.dimensiondoor.xyz
                  header_up Authorization "Bearer {{ .accessToken }}"
              }
          }
  data:
    - secretKey: accessToken
      remoteRef:
        key: k8s/voicemail-receiver
        property: NTFY_TOKEN
