---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: voicemail-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noresvport
  nfs:
    server: 192.168.1.27
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voicemail-data
  namespace: voicemail-receiver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: voicemail-nfs
  resources:
    requests:
      storage: 5Gi
