# Paperless-ngx document management (https://docs.paperless-ngx.com)
#
# Native NixOS module (services.paperless, nixpkgs 2.20.15). Data lives on
# the mergerfs/NFS pool (/srv/nfs/paperless -> /mnt/storage) for capacity.
# PostgreSQL provisioned locally via createLocally -> adds the `paperless` DB
# to theoden's existing postgres instance, which is already dumped by the
# `postgres-offsite` restic job (pg_dumpall). Document media is backed up by
# the `paperless-offsite` restic job in configuration.nix.
#
# Admin password rendered by vault-agent from OpenBao secret/nixos/paperless
# (field admin_password). Create it once before first boot:
#   bao kv put secret/nixos/paperless admin_password="$(openssl rand -base64 24)"
#
# PAPERLESS_SECRET_KEY is auto-generated by the module into dataDir and
# persists across restarts — no env file needed.
#
# OCR is CPU-only (no GPU on theoden); acceptable for a household archive.
# Exposed on :28981 (0.0.0.0) for direct LAN access. Front with k3s traefik
# at https://paperless.lan later — follow romm.nix pattern (IngressRoute +
# manual Endpoints to 192.168.1.27).
#
# Restore: DB from postgres-offsite (all.sql), media from paperless-offsite,
# then `paperless-manage document_index reindex` (whoosh index is re-derivable
# and excluded from backup).
{ config, lib, ... }:
{
  modules.vault-agent.secrets.paperless-admin-pw = {
    path = "secret/nixos/paperless";
    field = "admin_password";
    owner = config.services.paperless.user;
    group = config.users.users.${config.services.paperless.user}.group;
  };

  services.paperless = {
    enable = true;
    dataDir = "/srv/nfs/paperless";
    # mediaDir / consumptionDir default to ${dataDir}/{media,consume}.
    passwordFile = "/run/secrets/paperless-admin-pw";
    address = "0.0.0.0";
    port = 28981;
    database.createLocally = true;
    settings = {
      # Recursive consume so dropped folder trees ingest; subdirs become tags.
      PAPERLESS_CONSUMER_RECURSIVE = true;
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS = true;
      # PAPERLESS_URL left unset: paperless derives from the request Host
      # header, so http://theoden.lan:28981 and a future https://paperless.lan
      # both work without reconfig. Set a canonical URL when traefik lands.
    };
  };

  # Direct LAN access. Traefik IngressRoute is a follow-up.
  networking.firewall.allowedTCPPorts = [ 28981 ];

  # vault-agent renders /run/secrets/paperless-admin-pw, which the scheduler
  # loads via LoadCredential to reconcile the admin user on every start.
  # State on NFS is already covered by the module's RequiresMountsFor
  # (ReadWritePaths = data/media/consume dirs under /srv/nfs/paperless).
  systemd.services =
    lib.genAttrs
      [
        "paperless-scheduler"
        "paperless-task-queue"
        "paperless-consumer"
        "paperless-web"
      ]
      (_: {
        after = [ "vault-agent-default.service" ];
        wants = [ "vault-agent-default.service" ];
      });
}
