---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: romm-lan-tls
  namespace: romm
spec:
  secretName: romm-lan-tls
  issuerRef:
    name: lan-ca
    kind: ClusterIssuer
  dnsNames:
    - romm.lan
