---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zot-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noresvport
  nfs:
    server: 192.168.1.27
    path: /zot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-data
  namespace: zot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: zot-nfs
  resources:
    requests:
      storage: 100Gi
