apiVersion: v1
kind: Secret
metadata:
    name: zot-credentials
    namespace: zot
stringData:
    credentials.json: ENC[AES256_GCM,data:4nd8OIgVHCvL3SjvHPjFzMmeAqqU5xSEquRe4QY7gq/W9MEFoR3TySu75WYQRQdhIOOE8Leb2uV4ds+K1zpxVllOnY08THVCJeBP6xLKJS97I4ZHOFZpMW+LCfH31/UwE/piM1lDmjTgKuOJxcUsFvFA9DbHgfwd05KLLRAdVj3OYXHaHd//5+Vs/R51Ty3pdK5bUKtjdIxYz0wArexlNAd7zV8LN2TP78HMnVkHOZ0uljxYMOROH66es8uog+GKH8OC3AfyFLaytC3c2AeTf09VyoWsfYDSw8ZEBdGq/lSFA6iJ,iv:ncvuv9xNsFhbWasPAZQqaHNUFbXwckuFwt05GryYbwA=,tag:SqbYuxDKjh93kgSqGXtFOw==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZEhVb0xxY2RsMEpad3FX
            QkJRdVdMNGNkTDBqd1lqRjk1K2ppTnNCSTJzCkc2SkQ2RjF1WE5hVUthcEJYMVMy
            bm0rZFVnMXVJb2p1WEs4ZTRFRDRNcjQKLS0tIHdTekZadjJRcElJWHAwTG9XK3Zq
            VzFDcmhXZHZNTGFiODU1S215anc0bkEK/LX7hNmp91/7BDaUeL7GBookiFxbrbhX
            yt4gTDeBWV0UHX5npbAcR6poJA2WQjTU73leI/w3MivSEEh5elGKkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZVk0OGhZWm1vKytPTlk0
            K0RLcjIvZlpON2hXN3V5Q3pFVXRsVUcwSFZRCjU5a2F5Sy9tdEpaQnJEeERjTDVk
            a3V3dDdvbVdNMnBLdlhzU24xM0JJdWsKLS0tIC9CNmpDbXF0c1lJZGx5YU93dDZx
            NWgzTjRmZm9CVzdwejJPNngrQjBvSVUKgogHAEtvdzpFGHRzv/ID5GOYiNmPYq8v
            sM8mQfnIkpLEi+lJxAlNummWzrBk/mXnmiO9wqqeO781McCs12EJAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWXdleGlQZzlBRERvWUor
            THBVajRrTjhSREJsOFVEMEg0WHA2czZxSmhVCjl6QitBSmdNSGV2MVgyWG5UUC9S
            V0xSSnJsWHhCbFV2b3I3dU5SMTM5YVUKLS0tIFFhdnVOQXZtd3YvL0d3azRacVV1
            VlJSK0hkK2FIK2dHODRiVVZFV0swcU0KThxcjG/k1rLhAhMaK8q6JQzEhSQbIl1q
            DT8zyS8RVwqdvY1gWuHnkEmKyZHMc3w5y2ZyTZ3vxKVKTyewGBXlmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QjVKWEt2RnJmY3RCaXJH
            dmI5WnM4UFB6blpKQ0FUWGxxQjEwSHZycjBNClEveFAwWmhHMGhtTmRtbFNXVHZq
            Z3ZOQnh6ZHF4MWxFTlhFYXRYUEsyMzgKLS0tIHZYTFJKajkwTG91L1kyMk82cjJk
            RmZ5KzY2ZUFNeklwVUtWTlEzbkxYUUUK9rNV4WTbm0ZP+UEjjChfNQy6O5eAwaYC
            NITO57d7dw8kgym2HwGYHY2S38E4hYwl82Z/kHZNoaolHdAUei0IRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T15:34:51Z"
    mac: ENC[AES256_GCM,data:pVDfAJsue4isSLIpNpfbSXjf64Ha0cKh8CCLUvufERn4zxtDXQw8kWuyaqoS8STKUdGf7cncUeLPQAnD0jtR2lkwohjRBFvdg4AcWyEJ+rB832aNTFoOtk5GolpqxltF3cD/RcLcwC84EK3nSpyk2gHdGPD+H+4CAJkbA1MDYSg=,iv:szAObpvdjxsrOqQV5u0ydfxuAdCj0dj5oh5MaQdMGFQ=,tag:2F103jPlEnknD4d81JkNdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
