---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zot
  namespace: zot
spec:
  selector:
    matchLabels:
      app: zot
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
