---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: k8s/authentik
        property: secret-key
    - secretKey: postgres-password
      remoteRef:
        key: k8s/authentik
        property: postgres-password
    - secretKey: immich-client-secret
      remoteRef:
        key: k8s/authentik
        property: immich-client-secret
    - secretKey: openwebui-client-secret
      remoteRef:
        key: k8s/authentik
        property: openwebui-client-secret
    - secretKey: forgejo-client-secret
      remoteRef:
        key: k8s/authentik
        property: forgejo-client-secret
    - secretKey: lobechat-client-secret
      remoteRef:
        key: k8s/authentik
        property: lobechat-client-secret
