# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cakewallet = {
    pname = "cakewallet";
    version = "v5.9.0";
    src = fetchurl {
      url = "https://github.com/cake-tech/cake_wallet/releases/download/v5.9.0/Cake_Wallet_v5.9.0_Linux.tar.xz";
      sha256 = "sha256-MENigwkVIx89dWUjb84tv9XRdWkXDpIlK4eHdv3RQJE=";
    };
  };
  jacktook = {
    pname = "jacktook";
    version = "3b8a60fbd35629dcbd741ba2127ec6d96f4b978a";
    src = fetchFromGitHub {
      owner = "Sam-Max";
      repo = "plugin.video.jacktook";
      rev = "3b8a60fbd35629dcbd741ba2127ec6d96f4b978a";
      fetchSubmodules = false;
      sha256 = "sha256-+GjBvjjmn4ax43arap8OHGN3EbyIUAnGI9SesY8PCsk=";
    };
    date = "2026-02-26";
  };
  moondeck-buddy = {
    pname = "moondeck-buddy";
    version = "1.9.2";
    src = fetchurl {
      url = "https://github.com/FrogTheFrog/moondeck-buddy/releases/download/v1.9.2/MoonDeckBuddy-1.9.2-x86_64.AppImage";
      sha256 = "sha256-SfaqrBJJZlJwhSPLPUlwfvZ8RxIWrbwY6uys8ziRvek=";
    };
  };
  opendeck = {
    pname = "opendeck";
    version = "2.9.1";
    src = fetchurl {
      url = "https://github.com/nekename/OpenDeck/releases/download/v2.9.1/opendeck_2.9.1_amd64.AppImage";
      sha256 = "sha256-9PTViEMTBBkUWmuHbeWSIGL6AjiSXIGxTT399JyPXzs=";
    };
  };
}
