# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agent-lisp-paren-aid = {
    pname = "agent-lisp-paren-aid";
    version = "2.1.0";
    src = fetchurl {
      url = "https://github.com/kiyoka/agent-lisp-paren-aid/releases/download/2.1.0/agent-lisp-paren-aid-linux";
      sha256 = "sha256-xaTPFQyvISRAr9oWYYLTqnNHCVQwY4aSJfrMP2145XQ=";
    };
  };
  jacktook = {
    pname = "jacktook";
    version = "bc767f387049c85b08fbbc5128c0eef210315496";
    src = fetchFromGitHub {
      owner = "Sam-Max";
      repo = "plugin.video.jacktook";
      rev = "bc767f387049c85b08fbbc5128c0eef210315496";
      fetchSubmodules = false;
      sha256 = "sha256-zy0wHlY3bjZfxOz8Mfs7Jk6alzo8Tby/yZIQ+TE6bzY=";
    };
    date = "2026-06-17";
  };
  moondeck-buddy = {
    pname = "moondeck-buddy";
    version = "1.9.2";
    src = fetchurl {
      url = "https://github.com/FrogTheFrog/moondeck-buddy/releases/download/v1.9.2/MoonDeckBuddy-1.9.2-x86_64.AppImage";
      sha256 = "sha256-SfaqrBJJZlJwhSPLPUlwfvZ8RxIWrbwY6uys8ziRvek=";
    };
  };
  opendeck = {
    pname = "opendeck";
    version = "2.12.1";
    src = fetchurl {
      url = "https://github.com/nekename/OpenDeck/releases/download/v2.12.1/opendeck_2.12.1_amd64.AppImage";
      sha256 = "sha256-fxYNr/ZSiQw5UTWHz/Q6kJ6WjGQr9NO9dPbZ3rXFKXw=";
    };
  };
}
