# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cakewallet = {
    pname = "cakewallet";
    version = "v6.1.2";
    src = fetchurl {
      url = "https://github.com/cake-tech/cake_wallet/releases/download/v6.1.2/Cake_Wallet_v6.1.2_Linux.tar.xz";
      sha256 = "sha256-awZut6smNYb+HMPYNsRTKlW09PnqGFWCklQddcSXH7A=";
    };
  };
  hydra-launcher = {
    pname = "hydra-launcher";
    version = "3.9.8";
    src = fetchurl {
      url = "https://github.com/hydralauncher/hydra/releases/download/v3.9.8/hydralauncher-3.9.8.AppImage";
      sha256 = "sha256-jKhmcHfi3QuihTxIX73QRLfs8K7iH+lKxhCNpKJsumk=";
    };
  };
  jacktook = {
    pname = "jacktook";
    version = "e028c0c7290f8fd24836da61a88e3eb9908abad4";
    src = fetchFromGitHub {
      owner = "Sam-Max";
      repo = "plugin.video.jacktook";
      rev = "e028c0c7290f8fd24836da61a88e3eb9908abad4";
      fetchSubmodules = false;
      sha256 = "sha256-Kce5vuk7vf0mwGzMK61mRWQzW+LVO2raVKrYJeotFls=";
    };
    date = "2026-05-25";
  };
  moondeck-buddy = {
    pname = "moondeck-buddy";
    version = "1.9.2";
    src = fetchurl {
      url = "https://github.com/FrogTheFrog/moondeck-buddy/releases/download/v1.9.2/MoonDeckBuddy-1.9.2-x86_64.AppImage";
      sha256 = "sha256-SfaqrBJJZlJwhSPLPUlwfvZ8RxIWrbwY6uys8ziRvek=";
    };
  };
  opendeck = {
    pname = "opendeck";
    version = "2.12.0";
    src = fetchurl {
      url = "https://github.com/nekename/OpenDeck/releases/download/v2.12.0/opendeck_2.12.0_amd64.AppImage";
      sha256 = "sha256-W40GHZZImUpxmJfW9zc47dTkjMJ+NIfGAuXy/UvsRL4=";
    };
  };
}
