---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-packages-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: 192.168.1.27
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-packages
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: forgejo-packages-nfs
  resources:
    requests:
      storage: 50Gi
