---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: forgejo-runner
    creationPolicy: Owner
  data:
    - secretKey: runner
      remoteRef:
        key: k8s/forgejo-runner
        property: runner
    - secretKey: registry-token
      remoteRef:
        key: k8s/forgejo-runner
        property: registry-token
