---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stremio-secrets
  namespace: stremio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: stremio-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: k8s/stremio
        property: postgres-password
    - secretKey: proxy-password
      remoteRef:
        key: k8s/stremio
        property: proxy-password
    - secretKey: prowlarr-api-key
      remoteRef:
        key: k8s/stremio
        property: prowlarr-api-key
    - secretKey: torbox-api-key
      remoteRef:
        key: k8s/stremio
        property: torbox-api-key
