---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: longhorn-backup
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: nixos/backblaze
        property: key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: nixos/backblaze
        property: application_key
