# Generated by nixos-generate-config on the Steam Machine during
# `nixos-anywhere --generate-hardware-config`, then reformatted to satisfy
# this repo's pre-commit hooks (nixfmt, statix, deadnix). Content is
# unchanged: the `boot` keys are grouped in one block because statix rejects
# repeated flat `boot.` assignments, and the unused `pkgs` argument was
# dropped.
#
# Regenerate with:
#   nixos-anywhere --phases kexec \
#     --generate-hardware-config nixos-generate-config \
#       ./hosts/steammachine/hardware-configuration.nix \
#     --flake .#steammachine root@192.168.1.111
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # `--no-filesystems` is passed above, because disko owns / and /boot.
  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "usbhid"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
