---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: free-games-claimer-creds
  namespace: free-games-claimer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: free-games-claimer-creds
    creationPolicy: Owner
  data:
    - secretKey: EG_EMAIL
      remoteRef:
        key: k8s/free-games-claimer
        property: EG_EMAIL
    - secretKey: EG_PASSWORD
      remoteRef:
        key: k8s/free-games-claimer
        property: EG_PASSWORD
    - secretKey: EG_OTPKEY
      remoteRef:
        key: k8s/free-games-claimer
        property: EG_OTPKEY
    - secretKey: PG_EMAIL
      remoteRef:
        key: k8s/free-games-claimer
        property: PG_EMAIL
    - secretKey: PG_PASSWORD
      remoteRef:
        key: k8s/free-games-claimer
        property: PG_PASSWORD
    - secretKey: PG_OTPKEY
      remoteRef:
        key: k8s/free-games-claimer
        property: PG_OTPKEY
    - secretKey: GOG_EMAIL
      remoteRef:
        key: k8s/free-games-claimer
        property: GOG_EMAIL
    - secretKey: GOG_PASSWORD
      remoteRef:
        key: k8s/free-games-claimer
        property: GOG_PASSWORD
    - secretKey: GOG_OTPKEY
      remoteRef:
        key: k8s/free-games-claimer
        property: GOG_OTPKEY
    - secretKey: STEAM_USERNAME
      remoteRef:
        key: k8s/free-games-claimer
        property: STEAM_USERNAME
    - secretKey: STEAM_PASSWORD
      remoteRef:
        key: k8s/free-games-claimer
        property: STEAM_PASSWORD

