---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8sgpt-ai-secret
  namespace: k8sgpt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: k8sgpt-ai-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: k8s/k8sgpt
        property: api-key
