---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_ADGUARD_USER
      remoteRef:
        key: k8s/homepage
        property: HOMEPAGE_VAR_ADGUARD_USER
    - secretKey: HOMEPAGE_VAR_ADGUARD_PASS
      remoteRef:
        key: k8s/homepage
        property: HOMEPAGE_VAR_ADGUARD_PASS
    - secretKey: HOMEPAGE_VAR_HEADSCALE_KEY
      remoteRef:
        key: k8s/homepage
        property: HOMEPAGE_VAR_HEADSCALE_KEY
    - secretKey: HOMEPAGE_VAR_IMMICH_KEY
      remoteRef:
        key: k8s/homepage
        property: HOMEPAGE_VAR_IMMICH_KEY
