---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cliproxy-secrets
  namespace: cliproxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cliproxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: k8s/cliproxy
        property: api-key
    - secretKey: kimi-key
      remoteRef:
        key: k8s/cliproxy
        property: kimi-key
    - secretKey: management-secret
      remoteRef:
        key: k8s/cliproxy
        property: management-secret
    - secretKey: management-password
      remoteRef:
        key: k8s/cliproxy
        property: management-password
