---
apiVersion: v1
kind: Service
metadata:
  name: sillytavern
  namespace: sillytavern
spec:
  type: ClusterIP
  selector:
    app: sillytavern
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
