---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  interval: 1h
  chart:
    spec:
      chart: searxng
      version: "1.0.7"
      sourceRef:
        kind: HelmRepository
        name: kubitodev
        namespace: flux-system
      interval: 1h
  values:
    config:
      settings:
        use_default_settings: true
        server:
          limiter: false
          image_proxy: false
          method: "GET"
        search:
          formats:
            - html
            - json
          default_lang: "en"
        general:
          enable_metrics: false
      limiter: {}
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: searxng
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: searxng
              spec:
                template:
                  spec:
                    enableServiceLinks: false
