# Hardware configuration placeholder
# This file should be generated by nixos-generate-config on the target system
{ config, lib, ... }:

{
  imports = [ ];

  # PLACEHOLDER VALUES - Replace with actual hardware configuration
  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  # Filesystem configuration - MUST be updated for your actual system
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

    # Storage mount points for services
    "/mnt/storage1" = {
      device = "/dev/disk/by-label/storage1";
      fsType = "ext4";
      options = [ "nofail" ];
    };

    "/mnt/storage2" = {
      device = "/dev/disk/by-label/storage2";
      fsType = "ext4";
      options = [ "nofail" ];
    };
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
