# Example secrets file - copy to homeserver-secrets.yaml and fill in real values
# NEVER commit the actual homeserver-secrets.yaml file!

# Forgejo Configuration
forgejo:
  admin_password: "CHANGE_ME"
  runner_token: "CHANGE_ME"
  lfs_jwt_secret: "CHANGE_ME"

# Mullvad VPN for Torrents
mullvad:
  account: "CHANGE_ME"
  wireguard_private_key: "CHANGE_ME"
  wireguard_address: "10.0.0.1/32"
  server_public_key: "CHANGE_ME"
  server_endpoint: "1.2.3.4:51820"

# Home Assistant
homeassistant:
  secrets: |
    # Home Assistant secrets
    mqtt_password: "CHANGE_ME"
    signal_api_key: "CHANGE_ME"
  mqtt_password: "CHANGE_ME"

# Arr Stack API Keys
arr_stack:
  radarr_api_key: "CHANGE_ME"
  sonarr_api_key: "CHANGE_ME"
  prowlarr_api_key: "CHANGE_ME"
  qbittorrent_password: "CHANGE_ME"

# Reverse Proxy Domains
domains:
  base_domain: "example.com"
  forgejo: "git.example.com"
  jellyfin: "media.example.com"
  homeassistant: "homeassistant.local"
  radarr: "radarr.local"
  sonarr: "sonarr.local"
  prowlarr: "prowlarr.local"

# Service Ports
ports:
  forgejo_ssh: 2222
  homeassistant: 8123

# ACME email
acme:
  email: "admin@example.com"
