---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marinara-tls
  namespace: marinara
spec:
  secretName: marinara-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - marinara.dimensiondoor.xyz
