---
apiVersion: v1
kind: Service
metadata:
  name: marinara
  namespace: marinara
spec:
  type: ClusterIP
  selector:
    app: marinara
  ports:
    - name: http
      port: 7860
      targetPort: 7860
      protocol: TCP
