---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-prometheus-token
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: home-assistant-prometheus-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: k8s/monitoring
        property: token
