---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: open-webui-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: k8s/open-webui
        property: secret-key
    - secretKey: openai-api-keys
      remoteRef:
        key: k8s/open-webui
        property: openai-api-keys
    - secretKey: tavily-api-key
      remoteRef:
        key: k8s/open-webui
        property: tavily-api-key
    - secretKey: oauth_client_secret
      remoteRef:
        key: k8s/open-webui
        property: oauth_client_secret
