apiVersion: v1
kind: Secret
metadata:
    name: openbao-approle
    namespace: external-secrets
type: Opaque
stringData:
    role-id: ENC[AES256_GCM,data:yrN57FQw8/me5uxL7pBHEPoCeUhVs2KE5/75lfIn6fKXU4bf,iv:c0LYMljuzwRzRt4aSdwPA+OCCx4EYlGSGKKKCqJZvng=,tag:18OeTy67k2I77Co1YB18Aw==,type:str]
    secret-id: ENC[AES256_GCM,data:3GQXAZNTeV/k02mI5gMwtNkmN2ZKk/xP5ePYIhfgQeJyUAU3,iv:upVAvzI/BgN0bL9D8eIU3XirwJM7VntGuThs6V5dqCY=,tag:vACrFdQ6WWuBFr4PudQilg==,type:str]
sops:
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbjErYnhXWnVJVXJhZmdO
            QWF5SXpzRWhzclY2YW9KMVBaYkdoY1laTENZCnRpKy9PaXk3WmpFczM2YjM5Y1BW
            ayt3Y3M3clU0eG10dDVCSkdFeGtGRGcKLS0tIHdmS2tMWXVRTDdkWFFia210QkJN
            RzRlUHg1VTNYMk5VS0UzSjIvakFHWVEKhQPeEknNCPPM955xKGRhAdWY5QCHuHVJ
            pjzWump7KPwKIDCA3N62hBFywZspwqJ8sct7z4448bsA3gAOU4LP4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19yh3saqcmyyk7qr0zwgy44zz7fwrpzlrhzwx5ym7qsn0rneageuq3qdws5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc2pNT1hhSDZ0bFgwRmZt
            THZwYUNzdXBHbGxrWXJVc1hkMmM1M2tuaFMwCi9NWkVCZFZ5YVlOcDRMeW85cTg4
            Z3h1N0prSUd5eGsyTzYrdHdlM3pkM2sKLS0tIHA0YXZSRExhRTJGckp2QTFwaDNl
            VXphcDZlL3BnWm4yWHFJR3dPZCtVa1EKmh0iCT3S1aRub0Hs7/Bku4MDIWxwzorV
            noUW6fk3YTJJmvKQXEiwVETrovDt7MJWLGwds9dT9491TQpIhJT7fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xjpmwgcs5wzak0v0hgzzuyw09re5weqxmqhsy7vhmz967wrnjuyqgezjxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTEx1SzRzZDBPcXhZejlv
            Q0xYWEJoT1pYSjJYZWZjKzRyejNqWGdyc0djCjJwL3F6a05rdllRNFlaWVpWNjRJ
            Z3VBQnZ5dkRkOGFXZkl5UW1WMkt6ekEKLS0tIGRlbXFvUWcvOW8rRlZzMjNwV1Bz
            VjR5VTF6eGRxUUltbjJ2V05GWUxlQzAKumrFB0Oag56nu/B8TlzYZsXw7hQvEJsh
            ZL/DWhzbysfLsEz6UoekRlqiEI2mPGYs2Lt4hn0iazob1dQ6UKzNkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3mztcslxm6a60x8maclx6stwl82aka6435jz0p8vzm7nqc4uqnqqjqts3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUDVuR2pWZU1MbTU1Qlls
            ZDRqcGdPajBkWTl1Vks2U2NVcm1wQU5iV2pVCmNOWTBNV1UzTUpLSEwvaG1KNjVC
            eThjMFEwcGNtWHZwV3k3ZzFzL0JCelUKLS0tIHRPem80RTZjL2ZDS2tQZkprNFlP
            Z2tZZjQrZHp4WE5jZlhxOExXRVdhSEUKFYkjMSN9HsOvcfejLTnMjBQwNgvLhKGE
            aRxW/sEPRISHKFAC9nmDqX1XmFoU3RikSGR5rt/axcvpuF7iI6mJ0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T18:34:20Z"
    mac: ENC[AES256_GCM,data:zkxHJOt2SFrfSHlHivVqbmnIinwBrWR2/CscEIaqutys98YZXSDmz7ISMVUIEJ4yy9Hf+Qgl0h/caiOrdAReO87Fpjxf+FB3griH6KMufPrKi+uz24zCTSh2MkndgkBMPI7C5+tFuMLHjeusUDYRFJQHVaAmNDsPW3TuZNz34fE=,iv:ynVoaV6t1eZWdKejxzQRS5y5DGYIjqVyHBBlAUktRuE=,tag:VQjKUhUWbE+0TIAGkXtA8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
