#ENC[AES256_GCM,data:BSyMZOSljE5KOegBa1asTWfhuu4O1Q==,iv:1ZnPy55b7J1L6p1IkEv7Pgu9u0NHeZqN1YXS334A70U=,tag:n/gVC5TXugFPfU++2PXyCg==,type:comment]
forgejo:
    #ENC[AES256_GCM,data:KiMA8+czOOal5v4MITywVtrVvoIYJHQnr1ogkw5swe4ulETmhQ==,iv:l9PJ8GMAI5N85ONs7i/j3AhxnQaZdu7PikmqJjzy734=,tag:V92SBOerM+GalqkGuJqqkw==,type:comment]
    admin_password: ENC[AES256_GCM,data:wYV3CUHXZToK73qHjsnD,iv:qShXjaKOf+T1zm2HkxN940paTtAQYDEfFUfjzyuN9gE=,tag:lTs/8CmOEmjGpe2lgUZbbg==,type:str]
    #ENC[AES256_GCM,data:UMlquiif7BTCOW2d3xAPy/XfTvi8kw==,iv:TaQV20Htx7Ml+mGpYGrUY5VuaAnW0cpKHZSQ5fe7alE=,tag:779LsLUgxQH9iSu7ikFoow==,type:comment]
    runner_token: ENC[AES256_GCM,data:k0xo5BbR2c5MVWMyvGkeEr5m7quoDUZggwW6khqppse1tVEIYzkgTg==,iv:zYycCnGBwZ4WIfxeEYEEJApK3XwKDrh30dCRUPX8La4=,tag:bkdCpy0VMhyTsVl8vQb0qA==,type:str]
    #ENC[AES256_GCM,data:FHdJFcZ3uXVMpemiyqKAKaGDSg==,iv:o7VajTx20lmxnmpCGauJyGEdvhaFAxOgjqGbQvP3Lts=,tag:R4jGVp7cRLaw2GZdao3FeA==,type:comment]
    lfs_jwt_secret: ENC[AES256_GCM,data:PpHIbSjxLPyr2ciYOJNk84vN4nM=,iv:KbgF4xPgqflY3QPCD4dBWI8jd3dWOiSKkB1EZl3SPxQ=,tag:E+xd0dhdTHt/fn/N7b6BuQ==,type:str]
#ENC[AES256_GCM,data:3Q4gc6bv2/YSnNVnal/TvIeYpf7IOtELGw==,iv:4IIlSElkh2TQPSGnpfr5DJI2ct27vzT7B277PPxq7O0=,tag:PrtUnXcKeQpC99WU4msR3g==,type:comment]
mullvad:
    #ENC[AES256_GCM,data:7uy5a7rWTYm7tWp5HfWaMpCYBcr9Ag==,iv:dESEuQBSQ6ivF3x721Jhm+vaRfhz7lTYl8OI2wVkCYU=,tag:TZmSjEZFYw1bKGtlrCQoMg==,type:comment]
    account: ENC[AES256_GCM,data:6FVeh/9cRsNob+S+SQBfmQ==,iv:Obo4DT+T6cZ7hDBgJXVBhLb5bc3mlDfsSeq4ZOO4hVI=,tag:yTX/Qd9tbSYVC/8Wjp86kg==,type:str]
    wireguard_private_key: ENC[AES256_GCM,data:soDrCfhYWluI7OaBd1t62vRb/ddCVbODOPFVAM2YjUn3mhimmH/CB4Zk0ZA=,iv:7iuq1xkmEiX+oh2UQyNGKM5OnbezVfwwKGaRPDpqF2M=,tag:7RJslps5+QyYmTYNqM+9UQ==,type:str]
    #ENC[AES256_GCM,data:RrZ+PbFfJIQDwJL1lIdd2JVkVSJ/M5oWaEDkkFsyEQ2QgeIzYxMNaw==,iv:drbxzjqoXBTkNQssrwLEqnpD7QDPqwKLKMG/DEgXbCk=,tag:vM3i74MWJ30kBX9C8ParRg==,type:comment]
    #ENC[AES256_GCM,data:BkcsFjHQzO1RMpTCXgyzz/E=,iv:acO59dLFBy7VZc8GcQDoAe776bjiDMToV0SBU1eEEQg=,tag:iGQNvPp76630fqeDGYe0EQ==,type:comment]
    wireguard_address: ENC[AES256_GCM,data:TDHs4aTW3xiMWs3GDjrxAw==,iv:SLseXAsHYWcnGavMemWzWPlYg+p1we9WaREFPCE6LS0=,tag:Uz3C4fP5CNA3MdH5Miz2Xg==,type:str]
    server_public_key: ENC[AES256_GCM,data:Oy60atdwmVn2F/VDOb1sZA+eX99qjI1ZDuUDJ4VkjbuP6QjhLU9tgHftKto=,iv:uTsHfNixbmlGJEq14NhG9iBUPYi6UKueSrZs7FYcS5k=,tag:Eok8MChpPJrAHLxisf98QQ==,type:str]
    #ENC[AES256_GCM,data:A9yjdLqbShPKZJa3oTc=,iv:Yv2MTchstG4BqmvKHE+j7sf2uomhHQL5PIbOimMidXg=,tag:pVK5KOeNosXpJO5KdEbIrw==,type:comment]
    server_endpoint: ENC[AES256_GCM,data:8FdkIRG37CB82JLfXDmaHsyKLg==,iv:VWhWMa6kKB8vuJqI6mUUnMbg9V303FfBwjjEJPgbBmA=,tag:P9FzC+52w38BbUphOjQa0w==,type:str]
#ENC[AES256_GCM,data:2FVZ2MLz3Se9RnOSMpLO,iv:nJiYf/IOkI0q0DFOp6LXfqLoFjXoF6VXICzHANUVlMs=,tag:OQBCW8UT8F14tISMqjD1VA==,type:comment]
homeassistant:
    #ENC[AES256_GCM,data:iFY7CvqVQo0wbUDLBIkDESiEVZ2+MCTE3vSJyKq3KH25y+A/hVtdpk231m0aEacAlg==,iv:klzAm8D0Drm/wFoF239nfvrIaSX4oCpyuBLpALnEoQw=,tag:Btabl0Fg9ObpdHV+wC6Irg==,type:comment]
    signal_api_key: ENC[AES256_GCM,data:N8EqFcl91GmM,iv:ij122xGktdP/Vlk0DMlWvjYC4FqofaEOR6vOio2AD9s=,tag:kvN4jOStkxh/tnBZgCnvUQ==,type:str]
    mqtt_password: ENC[AES256_GCM,data:TgLCwM30joEe0AHunf09wYePGFyc/pU=,iv:gYsjlyjjGA5swFGzHNDCCgBU7UlBILxR6gBv9KOOv4c=,tag:iYFw5zf0CGJb0mdNmzfPFA==,type:str]
#ENC[AES256_GCM,data:NySl7EK601GLoPBz/qRRIKfeOg==,iv:6iOfB5Bga3Gcyc2H1rTTj6LQKqZW46rcTdfVtQ3qrk0=,tag:2pkEffNX4tyrWKUzPVicyg==,type:comment]
arr_stack:
    #ENC[AES256_GCM,data:kzbya6H224IznC5fJk0iRaw1Yw==,iv:+i0q98V3PQrUR1Dgo2lO+OhDYcdCGPp+GeWBP2++JNE=,tag:w+aOImODfbsrHehurE3xuQ==,type:comment]
    radarr_api_key: ENC[AES256_GCM,data:wOCueQkQV69pFEsgBa6/3aspERAd,iv:4N1z1YlmrYrhnwtqGvlmrbOx8PyB2ZQNG9RiChXdQSg=,tag:o9b8Zd1FDrNwqSBS5K0TkQ==,type:str]
    #ENC[AES256_GCM,data:w7iHZjIKOY7U4lhUEl1k5qoTQw==,iv:BGlHV7a2r6LGUt3BysNzaP0Q7H8o+gJXxmpfv0TA4Vo=,tag:Bq+Orl0XCf3zRPiS9CnXEA==,type:comment]
    sonarr_api_key: ENC[AES256_GCM,data:Gm6cNuoQ9CKGQkWhiEOKfplbnwHa,iv:qLUpxb4pumkI+j4itIvmrSXQE2s9oLX8eADaSS3vseM=,tag:AYdMadcfT0HqLuviRJB64g==,type:str]
    #ENC[AES256_GCM,data:tVzEAaUSWWVVSq891nfCzmKJpvJY,iv:B9Nyq84B0Tg9usqfgPMeSKR5doLd8B+zceCiwtW5EJk=,tag:58OgCHgqFsARl2ICo+2irQ==,type:comment]
    prowlarr_api_key: ENC[AES256_GCM,data:ci+br5+tMPMAEysoCfwPwZx1HsWA,iv:g9pUKaBw2WClMNWXdOHMtkVR5S3mC1fOlJJ63py2cqQ=,tag:lZ73orN+gShKimrrcZp2mQ==,type:str]
    #ENC[AES256_GCM,data:WflQ/MiyQ2S1N5B1rbky3+imJ5M=,iv:MHyqi3lfVBsPcoBhYzSCkn9jiy9rpZY4apu24GRC5cY=,tag:MgEFToeYRhUW+V6DBsM4iA==,type:comment]
    transmission_password: ENC[AES256_GCM,data:9uzjFgKJymTS,iv:BE6Lizsk9Ldf+/k4JXKwUUmTE0ec9vUh3+4WPU9251c=,tag:iIPDj/C6KhFriIUQt5tAkA==,type:str]
#ENC[AES256_GCM,data:Y4BgIegSHIHpcvMTjQN3eam1vfJUfg==,iv:3k55g26RgX7qQa8MJ/krxZi+vPEBBBMUJdu9Nm8CeyE=,tag:aUD0Mfr3UtYlVOSvmfOmww==,type:comment]
domains:
    base_domain: ENC[AES256_GCM,data:V2AylHR7bjU6Coug3X9EFEc=,iv:tabLjWycL1CORWOUtlC03/8SlbnbkXu5H+/2m+xdu0c=,tag:EHFHJjodRGX/5KsjJDEixg==,type:str]
    forgejo: ENC[AES256_GCM,data:s0KVICeo2INrKxaI2bHY7sfBqqMd,iv:bJIvcHeJPmmIarzI/fieBqdeTtx9FfViS9s9BRKwUa4=,tag:rIAQAr7z7rBFfe+VMNTP6w==,type:str]
    jellyfin: ENC[AES256_GCM,data:IKBx4z1G0zfZmKnmJraCF4BDR5ZfKiY=,iv:GYpJaAtHINahJBeFGrq8CLLUE7Y5cbfBPVUyfFOXG0U=,tag:2mKdICF6VIBx7rmj9y5KJg==,type:str]
    #ENC[AES256_GCM,data:YzNhWZNid856J0gyzyFrDG2+qqAr/Cxo8EaOdIvAXdPA7tm2nlJZK8AjPkQVfSDJv7r32zAi4o0RyACFZ02UjEzH,iv:0elwHeUw9Rcb/ZtYUOWyh5mLUoqr90WkrqWpU6SsNe0=,tag:WA80fLf6J2YBFVsSS1UhqA==,type:comment]
    #ENC[AES256_GCM,data:ykVUZlb5BJHwK4tlEDnGC9gQiYdWGddtWC7Yit4CajZGph4=,iv:Jp2WPUBX+5Biqta1KAw7wkCIxTF4yttB3HhA5CydkFU=,tag:4BbBNgYQb0tUmqxbTPrbsA==,type:comment]
    homeassistant: ENC[AES256_GCM,data:NdCFQc9XqvBfzWoGdN3Pk9iktQ==,iv:Us8FRYYAlZQLtRVA3nyB1toCqDjQfsQQCulu2pWUggE=,tag:zE4zXPSS7uSZCMgao+rVKQ==,type:str]
    #ENC[AES256_GCM,data:cH73HAk2l2uTVIRR6Ahw6dNTHIXXOYA/UXtCDBaUhGR48KY=,iv:Nu3/Wns5lypRDBcP4Evuob/1LvUcaoffyaXn+2M9rW8=,tag:Fk71VYcHnrhct2Yexm15ZA==,type:comment]
    radarr: ENC[AES256_GCM,data:p9QiwJ/MnJzPtn2i,iv:pBoMdJRMAVuIIS5hBG1CDNS7EfPn3XKttngT2cyxg2k=,tag:vedXKG9U8lj7OsYidMMHsg==,type:str]
    #ENC[AES256_GCM,data:843i2PWMwwtE8Voy48R6WfOF8YzLqnTbsvp9W2VIAwnXFaQ=,iv:cAmUlAoSiEfjmfIItEoA3fSoEdDtJRxzXJNiLYsaP6I=,tag:B/bo++dYHGbPnScSd1z49g==,type:comment]
    sonarr: ENC[AES256_GCM,data:kjSICuoZ3gGe+Jsz,iv:iDuTOnbhB1OiphVr+0sg/pHPLA+XYwl2xByaHaR3fmg=,tag:8a03MVMoeLbhzhkJj+RH5g==,type:str]
    #ENC[AES256_GCM,data:uqXkC2Zqkqol5DDfqWRlwz9i7tTuZzawv6xFJEftZGNLifw=,iv:fbtS09BdB+jc9QvP+r7erHKvf/cmUNZ1KkpOdmkYCrU=,tag:a8vYgBE5KFkfIKB9WdgZSg==,type:comment]
    prowlarr: ENC[AES256_GCM,data:vs4sL7LGIjmTLAe62gs=,iv:nkoQXmO7DGt4AmYlUoQk+dPVwGeBUl3LKESAo97IZGM=,tag:1+6991vVfLAcLcFvXVV96Q==,type:str]
#ENC[AES256_GCM,data:j3qybqKav+G8lBuiBiJqvq1xGBNtHp5VoHU5fVz+rhpaZvNedAKqo8HPhQ==,iv:nLZsqIXlLMMH19woWCxcOcwtFQI/732/VfmnjHR9KK0=,tag:OOvwEgKUlz8GNfcjud+q5g==,type:comment]
ports:
    #ENC[AES256_GCM,data:z/f8WVhI9+fJBX009fPrpvpQCvTZi6aeIpyBt0n7oroDnJHRyAMQyqXTeDePO0/n1zbCwU8=,iv:SXguZ1057KZ/vkDE8+ST3I0N2FDd5AGF7czowmhxdwA=,tag:C8DQ1wIyIk9ec/QI0otgHA==,type:comment]
    forgejo_ssh: ENC[AES256_GCM,data:Gh1w,iv:8OWyXU6Lw+Hk8LGAr0hO2F7YoaQ+l0GmNb7Ylw19Bbk=,tag:ahCcOSFOLxhxdQNnAO1dRQ==,type:int]
    #ENC[AES256_GCM,data:DftA9W+8JHY2AUJrkhYS0Tp7ZX14ERhOf/INM2B1ka/6fovIHJs=,iv:0YCBQ4zAE4m9s3HDJMPQ6332pKjT6fSG9WlDxjwHV48=,tag:AtmLoYLrrcvtFPuX3iie3g==,type:comment]
    homeassistant: ENC[AES256_GCM,data:kB2IAQ==,iv:WnX/Sa6M1bTXNzyLTyJIydwvAO1jZtPc1w+2kFLm2Z4=,tag:aXWgfQz3m52FnkiEq7Ihjw==,type:int]
    whisper: ENC[AES256_GCM,data:Xplf9aY=,iv:cFpq4GMkdr4jIaR72CHMZ+8iiUwhSkA7cmzesyx+0po=,tag:fOBhipw6u0FDLLzsKPDsRg==,type:int]
    piper: ENC[AES256_GCM,data:c5gK6Hs=,iv:KP/QlDodzkUsCAapHEz0fVOM1rln4sJR9sRYRJLZbxo=,tag:1hdMigPqDYIO2oki9g6mXg==,type:int]
    openwakeword: ENC[AES256_GCM,data:9Nz0GHQ=,iv:2O/c1A76eNO7j6GIzMBRZSn90ksM7qwcB6w8JYQnsAA=,tag:4ExEXbZDZMmW8D142K2QJw==,type:int]
    esphome: ENC[AES256_GCM,data:0akxzQ==,iv:Grpnu90RYYqab1I/k6GY/fZufHT4uMreb8Eoe3LHXb4=,tag:nVPj7IXH4KHpQwe39NTlWw==,type:int]
    mosquitto: ENC[AES256_GCM,data:HME59A==,iv:JTOqAXdJeEygD9BErrKOvoHiJKYe5ttG6TA93+qBEto=,tag:QvrDQml5sSdWWwY2i4AA6g==,type:int]
    #ENC[AES256_GCM,data:UB/IKl6erTD6asmGj6Jpq1++XA==,iv:eNS9g5sxLox3H/6rgyyK0VJ4qdbRbZpLqs35/PmK1YY=,tag:hMGOcnVMspQuXkJD77LJ9A==,type:comment]
    signal_cli: ENC[AES256_GCM,data:1F4ROA==,iv:tKVGaT1Gv0EZcXHvXIA//3gqgJE6tflHNwb1tyPGSdw=,tag:1gZfY6J4QBVJ+uTM+gdMfg==,type:int]
    jellyfin: ENC[AES256_GCM,data:LZfXCA==,iv:uVTrK1Ph2kTeadzDm6KDat/xpendzuumq16+9DORx4o=,tag:fXRYRIKFkyDOn3nKq8/NEA==,type:int]
    radarr: ENC[AES256_GCM,data:UGNdGg==,iv:DYgUB87UI6I/Up+Z+Xk4gPqZIczy1oOVVyETiYdsgvs=,tag:Lpn5mTYnxkYo2+iSY3/xrw==,type:int]
    sonarr: ENC[AES256_GCM,data:5WwxeQ==,iv:aGnGMcqAPFIva53yZJF81HL1CLb3zpjGy6eqirliStE=,tag:L9+R6N6qDL0MWVuGsccc8A==,type:int]
    prowlarr: ENC[AES256_GCM,data:K1Cctg==,iv:4jVx//gmpKOrzfWT56fXCdoMEFCzG0g0XkmDjYyD7i4=,tag:yfOdkiYBRbElMdBK1tDgxg==,type:int]
    qbittorrent: ENC[AES256_GCM,data:FTfG2g==,iv:TzWjBDJur0ZvGev/qehD1f5YmJSrSKeKn3rdxcJVBW0=,tag:uhijyiZXWtrMow3HWWNZ5g==,type:int]
#ENC[AES256_GCM,data:n3HuBYduXyk=,iv:RbveU108drIwecDUczZRb5BZHyC29ffhfi6G4m/alFI=,tag:AYHRoYLYOC9dqSEAtaRn2w==,type:comment]
acme:
    #ENC[AES256_GCM,data:QFNUu0HjO3wES0FSPqEtG7NSxM84pg==,iv:8GaqXBiFfeyNNx7QSsUmGYOaB+7rHwUZc0UN4oZKW2w=,tag:b7L64K8CEJZko0BPj/PopQ==,type:comment]
    email: ENC[AES256_GCM,data:KsQHHVUwIzzZE5s69oT0dRiZvfqWcch+,iv:TF1NJiolQKKiPPvdRd5M5j/onkOpgrmrqs3dFQh498E=,tag:KmnY9WZh9TwRyR2Ul4jJ+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h96q7q8m88zl0cwsskmlmxgelnf863978hzrukqa3alcst5pv4dq8syj4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieXNRV0N2MWJTRG9QMXd2
            QzBZckJZRkhxelFuY1d0aWYxbzZQQURCcVNJCk12dE9SZGp4M09RdkR5WHd4bTRl
            YmlNN1pqbXZOVTcvNm90WTc0cEJRZE0KLS0tIEZQYmVmZFpRMk95d1NzdEhtcllI
            Z05MNnp5Nm5BU3VIekFPS2RJQkE4ajAKrknwh+8xeTtwRKx5QUXpqxt1xl9ipAxA
            CJJuoIfGzuUycxW+2NW1QQBSh+mn5vKhXU91APThcRqdNoRUZlX6DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T00:51:38Z"
    mac: ENC[AES256_GCM,data:IJMV2ke3ZTiIrHw6X+3wxNfXnpMLgZUOusDVyHeKK2aiO/xRBvswYV1sCdqAHVZb2oR6WCBHH2dd36//kvsQoMedF12Hu2N7egTNtFvyVtOgocdEilxcBxoprLGeb/gsmCfWFcJkoMKmQxUiASQCgENI+3X3vxd/QRhpIcVApS4=,iv:NcsvGFZAwT6uEsuP8XbWF+LH5O5ct7/SPJeIlXQ86GY=,tag:PEOu6DSwR+X/PT5tL12EtQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
